export const ADD_TODO='ADD_TODO';
export const REMOVE_TODO='REMOVE_TODO';

export const PENDING_TODO='PENDING_TODO';

export const ADD_TODO_LOADING='ADD_TODO_LOADING';
export const ADD_TODO_SUCCESS='ADD_TODO_SUCCESS';
export const ADD_TODO_ERROR='ADD_TODO_ERROR';


export const GET_TODO_LOADING='GET_TODO_LOADING';
export const GET_TODO_SUCCESS='GET_TODO_SUCCESS';
export const GET_TODO_ERROR='GET_TODO_ERROR';

export const REMOVE_TODO_LOADING='REMOVE_TODO_LOADING';
export const REMOVE_TODO_SUCCESS='REMOVE_TODO_SUCCESS';
export const REMOVE_TODO_ERROR='REMOVE_TODO_ERROR';


export const TOGGLE_TODO_LOADING='TOGGLE_TODO_LOADING';
export const TOGGLE_TODO_SUCCESS='TOGGLE_TODO_SUCCESS';
export const TOGGLE_TODO_ERROR='TOGGLE_TODO_ERROR';

export const EDIT_TODO_LOADING='EDIT_TODO_LOADING';
export const EDIT_TODO_SUCCESS='EDIT_TODO_SUCCESS';
export const EDIT_TODO_ERROR='EDIT_TODO_ERROR';